version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "javascript"
    directory: "/backend"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
