export const config = {
  shortName: "Zeltlager",
  longName: "Zeltlager Wittlich",
  location: "Wershofen",
  // startDate: "2024-10-12",
  // endDate: "2024-10-19",
  minParticipationFee: 180,
  maxParticipationFee: 220,
  reducedMinParticipationFee: 140,
  reducedMaxParticipationFee: 180,
  maxParticipants: Infinity,
  year: "2024",
  iban: "DE69 5875 1230 0032 7144 61",
  leadershipMembers: [
    "Niklas Sips",
    "Enrico Schaaf",
    "Lena Ehlen",
    "Eva Thiel",
  ],
  domain: "zeltlager-wittlich.de",
} as const
